name: Deploy TFT Bot

on:
  push:
    branches: [ main ] # Trigger only on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Oracle VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tft-stat-bot
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 restart tft-bot